#!/bin/bash

T=$(sensors | awk -F'[+.]' '/^temp1/ {print $2}' | tail -n1);
LIM=70;

echo $(sensors | awk '/^temp1/ {print $2}' | tail -n1);

if [ $T -ge $LIM ]
then
	dunstify "Your laptop is getting too hot" -u critical;
fi
