#!/bin/sh

case $BLOCK_BUTTON in
	1) rofi-wifi-menu.sh;;
	6) st -e "$EDITOR" "$0" ;;
esac


[ $(cat /sys/class/net/e*/operstate) == up ] && echo 🌐 || \
[ $(cat /sys/class/net/wlp4s0/operstate) == down ] && echo "No internet" || \
echo "📶$(( $(awk -F'[ .]' '/^wlp/{print $5}' /proc/net/wireless) * 100 / 70 ))%"
